apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tsumnsso-prod
resources:
  - namespace.yaml
  - secret.yaml
  - ../../base
patches:
  - path: domain.json
    target:
      kind: Ingress
      name: sso-ingress
