apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sso-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-clusterissuer"
    nginx.ingress.kubernetes.io/proxy-body-size: "200m"
    nginx.ingress.kubernetes.io/app-root: /realms/inhouse/account

spec:
  tls:
    - hosts:
        - blabla.tsungmn.com
      secretName: gitops-tls
  rules:
    - host: blabla.tsungmn.com
      http:
        paths:
          - backend:
              service:
                name: sso-service
                port:
                  number: 80
            path: /
            pathType: Prefix
